### ISSUE TITLE
Turning off USB3 doesn't turn off power, but seems to only turn off communication on Pi 3B+

### ISSUE THREAD

**Issue by NovaViper** [OutsourcedGuru/OctoPrint-USBControl#3]
I have this strange issue where when I turn off USB3, it doesn't actually turn off the USB's power but instead disconnects the pi from the printer. Is this normal?

**Comment by OutsourcedGuru** [comment]
Can you provide the section of your `~/.octoprint/config.yaml` under `plugins` for this `USBControl`? It's possible that your 3B+ has an odd identifier that's not recognized.

**Comment by OutsourcedGuru** [comment]
Or, actually, it simply means that you've selected the USB port related to the printer itself. Read the README.md completely where it describes the scenario I saw with my own printer.

**Comment by NovaViper** [comment]
I notice that the only way I can actually turn off the printer is using the "turn off everything" option, which also turns off my camera.. and as far as with jumpers, the Ender 3's main board doesn't have any sort of jumper at all <_>

**Comment by OutsourcedGuru** [comment]
All this isn't expected to turn off the printer, merely to turn off the 5V line that's on one of the pins which is related to the printer. If by toggling all the USB ports on the Raspi to OFF the printer then turns off then this doesn't sound good; the printer itself should have its own power, right?

The expected behavior in half the cases (when the printer board is sinking 5V power from the Raspi) is that OctoPrint drops the serial connection to the printer. In theory, there's another case in which the printer board is built so that it's isolated from the 5V Raspi power and doesn't sink it; it may then continue to work while the print is going. And yet, it may or may not do the initial startup serial connection in this state since the 5V could be used to bring up the device driver for this port.

**Comment by NovaViper** [comment]
My printer's PSU is controlled by the Raspberry pi. and I want the printer itself to turn off all the way but because of the pi giving power via the printer's USB port, it still stays on even though the PSU is actually off

**Comment by OutsourcedGuru** [comment]
Ah... so you trigger the PSU to go off and then it IS sinking power over to the printer board. Gotcha. In this case if USB3 doesn't turn off that 5V power then it's possible that's not the actual device the Raspi assigned to the printer.

**Comment by NovaViper** [comment]
Stranger thing is.. all I see is USB2 and USB3, but no USB4 or 5.

**Comment by OutsourcedGuru** [comment]
Come to think of it, that's how I coded it to look for a 3B+ (given how the hubs work).

If you look under (something like) `~/oprint/lib/python2.7/site-packages/usbcontrol/bin`, there's an executable called `uhubctrl`. If you run it you might be able to find a magic combination which works for your scenario. It's usually `uhubctl -h` to get a list of options.

https://github.com/mvp/uhubctl (see Usage)

Additionally, `lsusb -v` should give you a list of the devices by port on your system. Note that `1-1` and `1-1.1` would be considered different when reviewing these. (Toggling off `1-1` might look like "everything went off" whereas `1-1.1` might be a single port.)

**Comment by NovaViper** [comment]
I did try using that app earlier, but it was really frustrating because it never seemed to find the correct ports (it just turned off everything instead of the USB only for the printer)

**Comment by OutsourcedGuru** [comment]
If you try toggling with just `1-1` for example, that will turn off the entire bus. It's necessary to add the decimal part for a single USB port on a 3B+.

I think that `lsusb -t` will allow you to see this better.

**Comment by NovaViper** [comment]
I'm going to close this because I just switched over to the SKR V1.3 board and it has a jumper that can prevent the printer from being powered by the USB
